name       : notepadqq
version    : 1.3.4
release    : 6
source     :
    - https://github.com/notepadqq/notepadqq/archive/v1.3.4.tar.gz : 4a8f387247bc8f65763ba6f2d33127dab1138ab3e77cd672301fc906f3801883
license    : GPL-3.0-or-later
component  : editor
summary    : Notepad++ like editor for Linux
description: |
    Notepadqq is a text editor designed from developers, for developers. With its more than 100 supported languages, it is the ideal editor for your daily tasks.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
optimize   :
    - lto
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
