name       : notepadqq
version    : 1.4.8
release    : 13
source     :
    - https://github.com/notepadqq/notepadqq/archive/v1.4.8.tar.gz : 13fba9abd84c59de27fbe92f74e2763b57588fcf9c88af10ec67313b0abbc9d0
license    : GPL-3.0-or-later
component  : editor
summary    : A simple, general-purpose editor for Linux
description: |
    Notepadqq is a text editor designed from developers, for developers. With its more than 100 supported languages, it is the ideal editor for your daily tasks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
optimize   :
    - lto
setup      : |
    %patch -p1 < $pkgfiles/appstream-remove-icon.patch
    %configure
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    # Make it easier to launch from terminal
    ln -sv /usr/bin/notepadqq $installdir/usr/bin/nqq
