name       : notepadqq
version    : 1.4.0
release    : 8
source     :
    - https://github.com/notepadqq/notepadqq/archive/v1.4.0.tar.gz : f295353224848c06fafcc71c7f6a38780a98890075ab33f0179181ebf21bad08
license    : GPL-3.0-or-later
component  : editor
summary    : Notepad++ like editor for Linux
description: |
    Notepadqq is a text editor designed from developers, for developers. With its more than 100 supported languages, it is the ideal editor for your daily tasks.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
optimize   :
    - lto
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
